### ISSUE TITLE
后台用户名如果多到需要翻页的时候，会翻页失败

### ISSUE THREAD

**Issue by bhzhu203** [go-ignite/ignite-admin#1]
后台用户名如果多到需要翻页的时候，会翻页失败

![_2018-03-14t06-38-54 898z](https://user-images.githubusercontent.com/3523160/37386987-a76dfab2-2795-11e8-9eee-ad844a52d46f.png)

**Comment by bhzhu203** [comment]
查出原因了  最新版本的js里少写了   v-on:change="pageChanged"

**Comment by TimothyYe** [comment]
@bhzhu203 厉害了，我们空了马上改一下

**Comment by 508869994** [comment]
好难搭建啊，这个！
